Update notify.yml

diff --git a/.github/workflows/notify.yml b/.github/workflows/notify.yml
--- a/.github/workflows/notify.yml
+++ b/.github/workflows/notify.yml
@@ -205,10 +205,10 @@ jobs:
             -d parse_mode=MarkdownV2 \
             -d disable_web_page_preview=true)
 
-echo "$RESPONSE" | grep -q '"ok":false'
-if [ $? -eq 0 ]; then
-  echo "❌ Failed to send Telegram notification."
-  exit 1
-else
-  echo "✅ Telegram notification sent successfully."
-fi
+            echo "$RESPONSE" | grep -q '"ok":false'
+            if [ $? -eq 0 ]; then
+             echo "❌ Failed to send Telegram notification."
+             exit 1
+            else
+            echo "✅ Telegram notification sent successfully."
+           fi
